---

apiVersion: rbac.authorization.k8s.io/v1

kind: RoleBinding

metadata:
  name: jane-binding
  namespace: dev

subjects:
- kind: ServiceAccount
  name: jane

roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin

