apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 70%
      maxSurge: 0
  template:
    metadata:
      name: web
      labels:
          app: web
    spec:

      initContainers:
      - name: init-myservice
        image: busybox:1.36.0-uclibc
        command: ['sh', '-c', 'wget -O- https://tinyurl.com/otus-k8s-intro | sh']
        volumeMounts:
        - name: app
          mountPath: /app

      containers:
      - name: web
        image: shurenbergen/angular-starter:v2.0
        livenessProbe:
          tcpSocket:
            port: 8000
        readinessProbe:
          httpGet:
            path: /
            port: 8000
        ports:
          - containerPort: 8000
        volumeMounts:
        - name: app
          mountPath: /app


      
      volumes:
      - name: app
        emptyDir: {}