---
ingress:
  enabled: true
  
  annotations:
    kubernetes.io/ingress.class: "nginx"
    kubernetes.io/ingress.allow-http: "true"
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-production"
    cert-manager.io/acme-challenge-type: "http01"
  
  hosts:
    - name: chartmuseum.${EXTERNALIP}.nip.io
      path: /
      tls: true
      tlsSecret: chartmuseum.${EXTERNALIP}.nip.io.secret
  
  certManager: true

env:
  open:
    # disable all routes prefixed with /api
    DISABLE_API: false