apiVersion: v1
kind: Secret
metadata:
  name: mysecret
  labels:
    app: minio
type: Opaque
data:
  # You can include additional key value pairs as you do with Opaque Secrets
  username: bWluaW8= # minio in base64
  password: bWluaW8xMjM= # minio123 in base64